### ISSUE TITLE
Problem: no temporary nsec is generated 

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/problems#11]
![PXL_20240919_103950099.MP.jpg](https://github.com/user-attachments/assets/920257e0-0c76-4464-bf09-945f02fa8545)

**Comment by Andrez092** [comment]
I think this will help you.
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive
