### ISSUE TITLE
problem: can't save drafts

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/problems#17]
problem: when logging a new problem, the user can't save a draft.

solution: check how amethyst is doing drafts, maybe there is a NIP for this. If there is no NIP, ping me and I will create one.

**Comment by bob2402** [comment]
The amethyst draft event uses [this NIP](https://github.com/nostr-protocol/nips/pull/1124/files), but it has not yet been merged into the master branch.

```js
{
  "kind": 31234,
  "tags": [
    ["d", "<identifier>"],
    ["k", "<kind of the draft event>"],
    ["e", "<anchor event event id>", "<relay-url>"],
    ["a", "<anchor event address>", "<relay-url>"],
  ],
  "content": nip44Encrypt(JSON.stringify(draft_event)),
  // other fields
}
```

**Comment by gsovereignty** [comment]
ok, instead of this, make drafts the exact same as the kind 31971 event, but publish it as 31970 instead.
