### ISSUE TITLE
problem: can't see characters remaining when adding new problem

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/problems#27]
the 140 and 560 length fields show an error when the user goes past them, but there's no indication of how many characters are remaining until they reach this point.

Also the fields still allow them to add more characters than the maximum

**Comment by bob2402** [comment]
So it's just suggesting a maximum character count without actually imposing a limit.

**Comment by gsovereignty** [comment]
I mean right now it is doing this in the UI, but there should be a hard limit in the input field so the user cannot exceed the maximum
